#' SIMULATION STUDY CODE FOR: 
#' Generalized pairwise comparisons for cluster randomized trials using win fractions
#' 
#' Author: Emma Davies Smith, esmith at hsph.harvard.edu
#' Date: 24JAN2025

# Load required libraries and source scripts
source('dependencies.R')

# Import simulation scenarios (generated by scenarios.R)
scenarios <- read.csv('./out/scenarios.csv')

# Simulate scenarios and store results 
results   <- simScenarios(scenarios, out='simResults.csv', seed=12345)

